# Nombre de la aplicación
spring.application.name=clinica

# Conexión a la base de datos PostgreSQL en Railway
spring.datasource.url=jdbc:postgresql://interchange.proxy.rlwy.net:34615/railway
spring.datasource.username=postgres
spring.datasource.password=WcIBHdAxwbllvoYMAsZLcuJdtPlHGixZ
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seguridad JWT
jwt.secret=41loj[n3K'qUMTIp4n.F==9m{cg%-zB+Va@!C)R18muZ
jwt.expiration=3600000
jwt.refresh=432000000

# Springdoc Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# Tiempos de expiración del JWT
jwt.expiration=3600000
jwt.refresh=432000000
